[package]
name = "memterm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi-control-codes = "0.0.4"
genawaiter = "0.99.1"
