[package]
name = "memterm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generator = "0.7.5"
lazy_static = "1.4.0"
unicode-width = "0.1.11"
